INSERT INTO currencies (name, description, rate) VALUES ( 'AED' ,  'United Arab Emirates Dirham' , 3.67273 );
INSERT INTO currencies (name, description, rate) VALUES ( 'AFN' ,  'Afghan Afghani' , 88.5038 );
INSERT INTO currencies (name, description, rate) VALUES ( 'ALL' ,  'Albanian Lek' , 107.3477 );
INSERT INTO currencies (name, description, rate) VALUES ( 'AMD' ,  'Armenian Dram' , 393.78348 );
INSERT INTO currencies (name, description, rate) VALUES ( 'ANG' ,  'Dutch Guilders' , 1.80238 );
INSERT INTO currencies (name, description, rate) VALUES ( 'AOA' ,  'Angolan Kwanza' , 510.6366 );
INSERT INTO currencies (name, description, rate) VALUES ( 'ARS' ,  'Argentine Peso' , 174.83244 );
INSERT INTO currencies (name, description, rate) VALUES ( 'AUD' ,  'Australian Dollar' , 1.49025 );
INSERT INTO currencies (name, description, rate) VALUES ( 'AWG' ,  'Aruban Florin' , 1.80051 );
INSERT INTO currencies (name, description, rate) VALUES ( 'AZN' ,  'Azerbaijani Manat' , 1.69994 );
INSERT INTO currencies (name, description, rate) VALUES ( 'BAM' ,  'Bosnia-Herzegovina Convertible Mark' , 1.84503 );
INSERT INTO currencies (name, description, rate) VALUES ( 'BBD' ,  'Barbadian Dollar' , 2.01904 );
INSERT INTO currencies (name, description, rate) VALUES ( 'BDT' ,  'Bangladeshi Taka' , 105.83946 );
INSERT INTO currencies (name, description, rate) VALUES ( 'BGN' ,  'Bulgarian Lev' , 1.84153 );
INSERT INTO currencies (name, description, rate) VALUES ( 'BHD' ,  'Bahraini Dinar' , 0.37692 );
INSERT INTO currencies (name, description, rate) VALUES ( 'BIF' ,  'Burundian Franc' , 2072.39733 );
INSERT INTO currencies (name, description, rate) VALUES ( 'BMD' ,  'Bermudian Dollar' , 0.99984 );
INSERT INTO currencies (name, description, rate) VALUES ( 'BND' ,  'Bruneian Dollar' , 1.35059 );
INSERT INTO currencies (name, description, rate) VALUES ( 'BOB' ,  'Bolivian Boliviano' , 6.93577 );
INSERT INTO currencies (name, description, rate) VALUES ( 'BRL' ,  'Brazilian Real' , 5.16547 );
INSERT INTO currencies (name, description, rate) VALUES ( 'BSD' ,  'Bahamian Dollar' , 1 );
INSERT INTO currencies (name, description, rate) VALUES ( 'BTN' ,  'Bhutanese Ngultrum' , 82.97745 );
INSERT INTO currencies (name, description, rate) VALUES ( 'BWP' ,  'Botswanan Pula' , 12.73784 );
INSERT INTO currencies (name, description, rate) VALUES ( 'BZD' ,  'Belizean Dollar' , 2.01584 );
INSERT INTO currencies (name, description, rate) VALUES ( 'CAD' ,  'Canadian Dollar' , 1.36027 );
INSERT INTO currencies (name, description, rate) VALUES ( 'CDF' ,  'Congolese Franc' , 2001.37037 );
INSERT INTO currencies (name, description, rate) VALUES ( 'CHF' ,  'Swiss Franc' , 0.93381 );
INSERT INTO currencies (name, description, rate) VALUES ( 'CLF' ,  'Chilean Unit of Account UF' , 0.0247 );
INSERT INTO currencies (name, description, rate) VALUES ( 'CLP' ,  'Chilean Peso' , 878.1446 );
INSERT INTO currencies (name, description, rate) VALUES ( 'CNH' ,  'Chinese Yuan Offshore' , 7.00605 );
INSERT INTO currencies (name, description, rate) VALUES ( 'CNY' ,  'Chinese Yuan' , 6.99097 );
INSERT INTO currencies (name, description, rate) VALUES ( 'COP' ,  'Colombian Peso' , 4733.47452 );
INSERT INTO currencies (name, description, rate) VALUES ( 'CUP' ,  'Cuban Peso' , 23.99942 );
INSERT INTO currencies (name, description, rate) VALUES ( 'CVE' ,  'Cape Verdean Escudo' , 104.29633 );
INSERT INTO currencies (name, description, rate) VALUES ( 'CZK' ,  'Czech Republic Koruna' , 22.77846 );
INSERT INTO currencies (name, description, rate) VALUES ( 'DJF' ,  'Djiboutian Franc' , 178.0059 );
INSERT INTO currencies (name, description, rate) VALUES ( 'DKK' ,  'Danish Krone' , 7.00195 );
INSERT INTO currencies (name, description, rate) VALUES ( 'DOP' ,  'Dominican Peso' , 55.754 );
INSERT INTO currencies (name, description, rate) VALUES ( 'DZD' ,  'Algerian Dinar' , 137.52751 );
INSERT INTO currencies (name, description, rate) VALUES ( 'EGP' ,  'Egyptian Pound' , 24.75121 );
INSERT INTO currencies (name, description, rate) VALUES ( 'ERN' ,  'Eritrean Nakfa' , 15.14322 );
INSERT INTO currencies (name, description, rate) VALUES ( 'ETB' ,  'Ethiopian Birr' , 53.56929 );
INSERT INTO currencies (name, description, rate) VALUES ( 'EUR' ,  'Euro' , 0.94152 );
INSERT INTO currencies (name, description, rate) VALUES ( 'FJD' ,  'Fijian Dollar' , 2.23635 );
INSERT INTO currencies (name, description, rate) VALUES ( 'FKP' ,  'Falkland Islands Pound' , 0.83053 );
INSERT INTO currencies (name, description, rate) VALUES ( 'GBP' ,  'British Pound Sterling' , 0.83053 );
INSERT INTO currencies (name, description, rate) VALUES ( 'GEL' ,  'Georgian Lari' , 2.6777 );
INSERT INTO currencies (name, description, rate) VALUES ( 'GHS' ,  'Ghanaian Cedi' , 10.00025 );
INSERT INTO currencies (name, description, rate) VALUES ( 'GIP' ,  'Gibraltar Pound' , 0.83053 );
INSERT INTO currencies (name, description, rate) VALUES ( 'GMD' ,  'Gambian Dalasi' , 63.00968 );
INSERT INTO currencies (name, description, rate) VALUES ( 'GNF' ,  'Guinean Franc' , 8620.9875 );
INSERT INTO currencies (name, description, rate) VALUES ( 'GTQ' ,  'Guatemalan Quetzal' , 7.8544 );
INSERT INTO currencies (name, description, rate) VALUES ( 'GYD' ,  'Guyanaese Dollar' , 209.48715 );
INSERT INTO currencies (name, description, rate) VALUES ( 'HKD' ,  'Hong Kong Dollar' , 7.8037 );
INSERT INTO currencies (name, description, rate) VALUES ( 'HNL' ,  'Honduran Lempira' , 24.6773 );
INSERT INTO currencies (name, description, rate) VALUES ( 'HRK' ,  'Croatian Kuna' , 7.11071 );
INSERT INTO currencies (name, description, rate) VALUES ( 'HTG' ,  'Haitian Gourde' , 147.00054 );
INSERT INTO currencies (name, description, rate) VALUES ( 'HUF' ,  'Hungarian Forint' , 376.65961 );
INSERT INTO currencies (name, description, rate) VALUES ( 'IDR' ,  'Indonesian Rupiah' , 15591.5452 );
INSERT INTO currencies (name, description, rate) VALUES ( 'ILS' ,  'Israeli New Sheqel' , 3.50392 );
INSERT INTO currencies (name, description, rate) VALUES ( 'INR' ,  'Indian Rupee' , 82.80096 );
INSERT INTO currencies (name, description, rate) VALUES ( 'IQD' ,  'Iraqi Dinar' , 1459.55733 );
INSERT INTO currencies (name, description, rate) VALUES ( 'IRR' ,  'Iranian Rial' , 42065.11358 );
INSERT INTO currencies (name, description, rate) VALUES ( 'ISK' ,  'Icelandic Krona' , 143.41016 );
INSERT INTO currencies (name, description, rate) VALUES ( 'JMD' ,  'Jamaican Dollar' , 152.96209 );
INSERT INTO currencies (name, description, rate) VALUES ( 'JOD' ,  'Jordanian Dinar' , 0.70921 );
INSERT INTO currencies (name, description, rate) VALUES ( 'JPY' ,  'Japanese Yen' , 132.86325 );
INSERT INTO currencies (name, description, rate) VALUES ( 'KES' ,  'Kenyan Shilling' , 123.25983 );
INSERT INTO currencies (name, description, rate) VALUES ( 'KGS' ,  'Kyrgystani Som' , 85.67584 );
INSERT INTO currencies (name, description, rate) VALUES ( 'KHR' ,  'Cambodian Riel' , 4114.29758 );
INSERT INTO currencies (name, description, rate) VALUES ( 'KMF' ,  'Comorian Franc' , 464.29052 );
INSERT INTO currencies (name, description, rate) VALUES ( 'KPW' ,  'North Korean Won' , 900.73502 );
INSERT INTO currencies (name, description, rate) VALUES ( 'KRW' ,  'South Korean Won' , 1282.36369 );
INSERT INTO currencies (name, description, rate) VALUES ( 'KWD' ,  'Kuwaiti Dinar' , 0.30646 );
INSERT INTO currencies (name, description, rate) VALUES ( 'KYD' ,  'Caymanian Dollar' , 0.82997 );
INSERT INTO currencies (name, description, rate) VALUES ( 'KZT' ,  'Kazakhstani Tenge' , 461.72335 );
INSERT INTO currencies (name, description, rate) VALUES ( 'LAK' ,  'Laotian Kip' , 17346.04045 );
INSERT INTO currencies (name, description, rate) VALUES ( 'LBP' ,  'Lebanese Pound' , 1512.37075 );
INSERT INTO currencies (name, description, rate) VALUES ( 'LKR' ,  'Sri Lankan Rupee' , 365.48648 );
INSERT INTO currencies (name, description, rate) VALUES ( 'LRD' ,  'Liberian Dollar' , 154.59408 );
INSERT INTO currencies (name, description, rate) VALUES ( 'LSL' ,  'Basotho Maloti' , 16.98908 );
INSERT INTO currencies (name, description, rate) VALUES ( 'LYD' ,  'Libyan Dinar' , 4.81785 );
INSERT INTO currencies (name, description, rate) VALUES ( 'MAD' ,  'Moroccan Dirham' , 10.50147 );
INSERT INTO currencies (name, description, rate) VALUES ( 'MDL' ,  'Moldovan Leu' , 19.20286 );
INSERT INTO currencies (name, description, rate) VALUES ( 'MGA' ,  'Malagasy Ariary' , 4442.14941 );
INSERT INTO currencies (name, description, rate) VALUES ( 'MKD' ,  'Macedonian Denar' , 57.98447 );
INSERT INTO currencies (name, description, rate) VALUES ( 'MMK' ,  'Myanma Kyat' , 2100.29484 );
INSERT INTO currencies (name, description, rate) VALUES ( 'MNT' ,  'Mongolian Tugrik' , 3434.48362 );
INSERT INTO currencies (name, description, rate) VALUES ( 'MOP' ,  'Macanese Pataca' , 8.04158 );
INSERT INTO currencies (name, description, rate) VALUES ( 'MRU' ,  'Mauritanian Ouguiya' , 37.10261 );
INSERT INTO currencies (name, description, rate) VALUES ( 'MUR' ,  'Mauritian Rupee' , 44.2563 );
INSERT INTO currencies (name, description, rate) VALUES ( 'MVR' ,  'Maldivian Rufiyaa' , 15.46265 );
INSERT INTO currencies (name, description, rate) VALUES ( 'MWK' ,  'Malawian Kwacha' , 1024.23487 );
INSERT INTO currencies (name, description, rate) VALUES ( 'MXN' ,  'Mexican Peso' , 19.36921 );
INSERT INTO currencies (name, description, rate) VALUES ( 'MYR' ,  'Malaysian Ringgit' , 4.42568 );
INSERT INTO currencies (name, description, rate) VALUES ( 'MZN' ,  'Mozambican Metical' , 64.11885 );
INSERT INTO currencies (name, description, rate) VALUES ( 'NAD' ,  'Namibian Dollar' , 17.03476 );
INSERT INTO currencies (name, description, rate) VALUES ( 'NGN' ,  'Nigerian Naira' , 446.68826 );
INSERT INTO currencies (name, description, rate) VALUES ( 'NOK' ,  'Norwegian Krone' , 9.86994 );
INSERT INTO currencies (name, description, rate) VALUES ( 'NPR' ,  'Nepalese Rupee' , 132.57257 );
INSERT INTO currencies (name, description, rate) VALUES ( 'NZD' ,  'New Zealand Dollar' , 1.59022 );
INSERT INTO currencies (name, description, rate) VALUES ( 'OMR' ,  'Omani Rial' , 0.38491 );
INSERT INTO currencies (name, description, rate) VALUES ( 'PAB' ,  'Panamanian Balboa' , 0.99932 );
INSERT INTO currencies (name, description, rate) VALUES ( 'PEN' ,  'Peruvian Nuevo Sol' , 3.82121 );
INSERT INTO currencies (name, description, rate) VALUES ( 'PGK' ,  'Papua New Guinean Kina' , 3.52479 );
INSERT INTO currencies (name, description, rate) VALUES ( 'PHP' ,  'Philippine Peso' , 55.23276 );
INSERT INTO currencies (name, description, rate) VALUES ( 'PKR' ,  'Pakistani Rupee' , 226.37515 );
INSERT INTO currencies (name, description, rate) VALUES ( 'PLN' ,  'Polish Zloty' , 4.37126 );
INSERT INTO currencies (name, description, rate) VALUES ( 'PYG' ,  'Paraguayan Guarani' , 7314.1813 );
INSERT INTO currencies (name, description, rate) VALUES ( 'QAR' ,  'Qatari Rial' , 3.6641 );
INSERT INTO currencies (name, description, rate) VALUES ( 'RON' ,  'Romanian Leu' , 4.61791 );
INSERT INTO currencies (name, description, rate) VALUES ( 'RSD' ,  'Serbian Dinar' , 110.45139 );
INSERT INTO currencies (name, description, rate) VALUES ( 'RUB' ,  'Russian Ruble' , 70.19484 );
INSERT INTO currencies (name, description, rate) VALUES ( 'RWF' ,  'Rwandan Franc' , 1066.75802 );
INSERT INTO currencies (name, description, rate) VALUES ( 'SAR' ,  'Saudi Arabian Riyal' , 3.7611 );
INSERT INTO currencies (name, description, rate) VALUES ( 'SCR' ,  'Seychellois Rupee' , 14.26668 );
INSERT INTO currencies (name, description, rate) VALUES ( 'SDG' ,  'Sudanese Pound' , 566.75969 );
INSERT INTO currencies (name, description, rate) VALUES ( 'SEK' ,  'Swedish Krona' , 10.51684 );
INSERT INTO currencies (name, description, rate) VALUES ( 'SGD' ,  'Singapore Dollar' , 1.35059 );
INSERT INTO currencies (name, description, rate) VALUES ( 'SHP' ,  'Saint Helena Pound' , 0.83053 );
INSERT INTO currencies (name, description, rate) VALUES ( 'SLL' ,  'Sierra Leonean Leone' , 18819.65035 );
INSERT INTO currencies (name, description, rate) VALUES ( 'SOS' ,  'Somali Shilling' , 568.46144 );
INSERT INTO currencies (name, description, rate) VALUES ( 'SRD' ,  'Surinamese Dollar' , 31.6011 );
INSERT INTO currencies (name, description, rate) VALUES ( 'SYP' ,  'Syrian Pound' , 2512.77771 );
INSERT INTO currencies (name, description, rate) VALUES ( 'SZL' ,  'Swazi Emalangeni' , 16.98908 );
INSERT INTO currencies (name, description, rate) VALUES ( 'THB' ,  'Thai Baht' , 34.78934 );
INSERT INTO currencies (name, description, rate) VALUES ( 'TJS' ,  'Tajikistani Somoni' , 10.21187 );
INSERT INTO currencies (name, description, rate) VALUES ( 'TMT' ,  'Turkmenistani Manat' , 3.49469 );
INSERT INTO currencies (name, description, rate) VALUES ( 'TND' ,  'Tunisian Dinar' , 3.12686 );
INSERT INTO currencies (name, description, rate) VALUES ( 'TOP' ,  'Tongan Paanga' , 2.34818 );
INSERT INTO currencies (name, description, rate) VALUES ( 'TRY' ,  'Turkish Lira' , 18.68394 );
INSERT INTO currencies (name, description, rate) VALUES ( 'TTD' ,  'Trinidad and Tobago Dollar' , 6.78908 );
INSERT INTO currencies (name, description, rate) VALUES ( 'TWD' ,  'Taiwan New Dollar' , 30.77497 );
INSERT INTO currencies (name, description, rate) VALUES ( 'TZS' ,  'Tanzanian Shilling' , 2334.04759 );
INSERT INTO currencies (name, description, rate) VALUES ( 'UAH' ,  'Ukrainian Hryvnia' , 36.93302 );
INSERT INTO currencies (name, description, rate) VALUES ( 'UGX' ,  'Ugandan Shilling' , 3638.91034 );
INSERT INTO currencies (name, description, rate) VALUES ( 'USD' ,  'United States Dollar' , 1 );
INSERT INTO currencies (name, description, rate) VALUES ( 'UYU' ,  'Uruguayan Peso' , 38.60969 );
INSERT INTO currencies (name, description, rate) VALUES ( 'UZS' ,  'Uzbekistan Som' , 11206.92662 );
INSERT INTO currencies (name, description, rate) VALUES ( 'VND' ,  'Vietnamese Dong' , 23582.65853 );
INSERT INTO currencies (name, description, rate) VALUES ( 'VUV' ,  'Ni-Vanuatu Vatu' , 120.99747 );
INSERT INTO currencies (name, description, rate) VALUES ( 'WST' ,  'Samoan Tala' , 2.72045 );
INSERT INTO currencies (name, description, rate) VALUES ( 'XAF' ,  'CFA Franc BEAC' , 626.97978 );
INSERT INTO currencies (name, description, rate) VALUES ( 'XCD' ,  'East Caribbean Dollar' , 2.7098 );
INSERT INTO currencies (name, description, rate) VALUES ( 'XDR' ,  'Special Drawing Rights' , 0.75304 );
INSERT INTO currencies (name, description, rate) VALUES ( 'XOF' ,  'CFA Franc BCEAO' , 617.63714 );
INSERT INTO currencies (name, description, rate) VALUES ( 'XPF' ,  'CFP Franc' , 112.52523 );
INSERT INTO currencies (name, description, rate) VALUES ( 'YER' ,  'Yemeni Rial' , 250.24791 );
INSERT INTO currencies (name, description, rate) VALUES ( 'ZAR' ,  'South African Rand' , 16.98709 );
INSERT INTO currencies (name, description, rate) VALUES ( 'ZMW' ,  'Zambian Kwacha', 17.98563 );